### ISSUE TITLE
[BUG] Can't load index data(404 Error)

### ISSUE THREAD

**Issue by Ariette** [ALeafWolf/NXX-Toolbox#2]
It fails to load data(404 error) after implementing graphql.

This is the Chrome console log message.

```
Error: Http failure response for https://realm.mongodb.com/api/client/v2.0/app/tearsofthemisdb-dznen/graphql: 404 OK
```

**Comment by ALeafWolf** [comment]
On which page/pages are you encounter this error? Any may you show me the screenshot of the console?

**Comment by Ariette** [comment]
https://www.nxxtoolbox.com/cards
https://www.nxxtoolbox.com/skills
https://www.nxxtoolbox.com/vision-history
https://www.nxxtoolbox.com/merch-list
https://www.nxxtoolbox.com/card-selection
...
I think it occurs on every page which need to load data from db server.

Here's the screenshot of the console.
![image](https://user-images.githubusercontent.com/10518158/129206177-467f26d9-faa3-4fbf-bc2e-52a089b991f1.png)

The error by `card:1` is because of github pages SPA support, so that's not a matter.
The error by `realm.mongodb.com/~` is the problem.

**Comment by ALeafWolf** [comment]
That's strange, I did not get any 404 on all the pages required graphql. I test on chrome, firefox and edge, and test on different devices, everything can load. Can you show me the screenshot under Network tab at dev tool. I need to check out your graphql request with its header.
![image](https://user-images.githubusercontent.com/51769728/129209143-e62b1989-159b-4973-97a5-dc8e05e33d7e.png)

**Comment by Ariette** [comment]
Here's my log.

![image](https://user-images.githubusercontent.com/10518158/129211474-5a26cebb-daa2-4a21-868e-368b9348a136.png)
![image](https://user-images.githubusercontent.com/10518158/129211545-2aa16b16-6594-4881-b940-7a644453ab68.png)

I tested on edge(desktop) and mobile chrome, but in all cases, it could not load the data.
I also tested with VPN but the same error occured, so it's not becuase of my network settings.

**Comment by ALeafWolf** [comment]
Hmm that's nasty. Because I cannot get any 404 error on my end, so I cannot find out where is the error come from, need some test from your side. Would you mind to help me on test the api? If so then I can find out the problem that is came from api itself or the website? 
And if possible, would you ask people from your region to check the site, to see if the data can load?

**Comment by Ariette** [comment]
I already asked my friends to test the site, but they also failed to load the data.
By the way, I found the 404 response contains this message.

```
{"error":"cannot find app using Client App ID 'tearsofthemisdb-dznen'"}
```

This is the reponse body of the 404 response.
I think it might be helpful to solve the problem.

**Comment by ALeafWolf** [comment]
I did some test with vpn on different regions too, and it just cannot load on certain region. Would you provide the region you are in so I can report this issue to the api provider?

**Comment by Ariette** [comment]
I'm in Korea, and I also tested in Japan VPN which also can't load the data.
Thank you.

**Comment by ALeafWolf** [comment]
Got it, I'll feed you the latest update once I receive the response. Thank you for reporting this to me!

**Comment by ALeafWolf** [comment]
Hi there, I just migrate back to my old api for now, could you check on your side that are data able to load?

**Comment by Ariette** [comment]
yes, it works well!
